backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "Blog Posts"
    label: "blog"
    folder: "content/blog"
    editor:
      preview: true
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
      - label: "Tag"
        name: "tag"
        widget: "list"
      - label: Date
        name: date
        widget: date
  - name: "info"
    label: Info
    folder: "content/home"
    editor:
      preview: true
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - name: "title"
        label: Title
      - name: "Index"
        label: index
        widget: number
      - name: "content"
        label: Content
        widget: "markdown"
